### PR TITLE
Prepare document for publication as VCWG Draft NOTE.

### PR DESCRIPTION
**Pull request by msporny**
Per the consensus achieved in issue #304, this PR prepares the VC API specification for publication as a W3C VCWG Draft Note by removing all material that was agreed to be removed by the CCG VC API Work Item group.

The expectation is that, if approved by the CCG, the "VC API v0.3" will be published as a FCGS and then copied to VCWG for publication as a W3C VCWG Draft Note.

NOTE: This is a DRAFT PR, is destructive of content, and MUST NOT be merged into the main branch. One potential future is that this particular branch's history will be moved to VCWG for publication, but the CCG branches and issues will remain here. How we will execute on this is a topic of ongoing discussion.

***
<a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-api/pull/320.html" title="Last updated on Nov 22, 2022, 4:01 PM UTC (54294b0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vc-api/320/f12d687...54294b0.html" title="Last updated on Nov 22, 2022, 4:01 PM UTC (54294b0)">Diff</a>

### CODE REVIEW

**Review by mkhraisha — COMMENTED** [review]
Not sure if this is a bug in the preview, but all the text from many unrelated sections is gone, for example: 
image

is now:
image

Also I note you removed many files, beyond just the index.html changes to exchanges, was this intended?

**Comment by msporny** [comment]
> Not sure if this is a bug in the preview

It's a bug in the preview. PR Preview doesn't publish any of the .js or .yml files by default. We'll have to investigate how to make it do that.

**Review by mkhraisha — APPROVED** [review]
LGTM

**Review by dlongley — APPROVED** [review]
RSLGTM

**Comment by TallTed** [comment]
For those who understand [LGTM](https://github.com/w3c-ccg/vc-api/pull/320#pullrequestreview-1162446500) ("Looks Good To Me") but (and) don't understand [RSLGTM](https://github.com/w3c-ccg/vc-api/pull/320#pullrequestreview-1163905632):

Other repos define it as "Rubber-Stamp Looks Good To Me", where the reviewer is approving without doing a full code review.  I'm guessing that's @dlongley's meaning.

**Comment by aljones15** [comment]
> 

Just so this is known: you can see the latest `index.html` with javascript and stylings by running

```js
npm run serveIndex
```

I just did that and the sections are there. The sections are added by a script that formats the open api yaml files into the documentation.

**Comment by msporny** [comment]
It's clear that there are a small minority of members of the VCWG that are hostile to adopting this as a work item at this point in time. We can continue to incubate the VC API in the CCG, get more implementation experience (beyond the 17+ implementers at present), and try again when the winds are blowing in our favor.

I'm going to close this PR if there are no objections in 7 days.

**Comment by msporny** [comment]
@msporny wrote:
> I'm going to close this PR if there are no objections in 7 days.

No objections, closing.

**Pull request closed without merging**
